[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  VITE_SUPABASE_URL = "https://xotjsplwpmhaopvpsfjm.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_9vnvSONGCMIAt0d3pAnRGA_Q98ZORW6"
  NEXT_PUBLIC_SUPABASE_URL = "https://xotjsplwpmhaopvpsfjm.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_9vnvSONGCMIAt0d3pAnRGA_Q98ZORW6"
  VITE_GOOGLE_CLIENT_ID = "1065078894672-rmp5kp8vfjns5rn9kp5psfp16g691043.apps.googleusercontent.com"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
